apiVersion: apps/v1
kind: Deployment
metadata:
  name: grafana
spec:
  replicas: 1
  selector:
    matchLabels:
      app: grafana
  template:
    metadata:
      name: grafana
      labels:
        app: grafana
    spec:
      containers:
      - name: grafana
        image: grafana/grafana:latest
        ports:
        - name: grafana
          containerPort: 3000
        volumeMounts:
          - mountPath: /var/lib/grafana
            name: grafana-storage

          - mountPath: /etc/grafana/provisioning/datasources
            name: grafana-datasources
            readOnly: false

          - mountPath: /etc/grafana/provisioning/dashboards
            name: grafana-dashboards-config

          - mountPath: /var/lib/grafana/dashboards
            name: grafana-dashboards-schema
            readOnly: false
      volumes:
        - name: grafana-storage
          emptyDir: {}

        - name: grafana-datasources
          configMap:
              defaultMode: 420
              name: grafana-datasources

        - name: grafana-dashboards-config
          configMap:
            name: grafana-dashboards

        - name: grafana-dashboards-schema
          hostPath:
            path: /data/mpss2020/ipfs-learning-tangle/grafana/dashboards
            type: Directory