apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.21.0 ()
  creationTimestamp: null
  labels:
    io.kompose.service: iota-visualization
  name: iota-visualization
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: iota-visualization
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert
        kompose.version: 1.21.0 ()
      creationTimestamp: null
      labels:
        io.kompose.service: iota-visualization
    spec:
      imagePullSecrets:
        - name: regcred
      containers:
      - image: hpimpss2020/learning-tangle:iota_visualization-x86
        imagePullPolicy: Always
        name: iota-visualization
        ports:
        - containerPort: 9000
        resources: {}
      restartPolicy: Always
      serviceAccountName: ""
      volumes: null
status: {}
