FROM rs22/tensorflow-aarch64-v1
ARG IPFS_VERSION=0.6.0

USER root

WORKDIR /
RUN mkdir logs

RUN apt-get update \
    && apt-get install -y dnsutils

RUN apt install -y iproute2 libatlas-base-dev

RUN mkdir /tmp/go-ipfs \
    && curl -sL https://ipfs.io/ipns/dist.ipfs.io/go-ipfs/v${IPFS_VERSION}/go-ipfs_v${IPFS_VERSION}_linux-arm64.tar.gz | tar xz -C /tmp/go-ipfs --strip 1 \
    && cd /tmp/go-ipfs && ./install.sh \
    && rm -rf /tmp/ipfs

RUN echo "[global]\nextra-index-url=https://www.piwheels.org/simple" >> /etc/pip.conf

WORKDIR /app
RUN pip3 uninstall -y enum34
COPY tangle/ipfs/peer/docker/requirements.arm64.txt ./requirements.txt
RUN pip3 install -r requirements.txt

COPY tangle/ipfs/peer/docker/ipfs_entrypoint /usr/bin/ipfs_entrypoint
COPY tangle/ipfs/peer/docker/entrypoint.sh .
COPY tangle/ipfs/peer/docker/manual_garbage_collection.sh .

COPY tangle /home/ubuntu/python3-venv/lib/python3.7/site-packages/tangle/

EXPOSE 4001
EXPOSE 8000

ENV PYTHONUNBUFFERED=TRUE
ENTRYPOINT ["./entrypoint.sh"]
