{
 "title": "IPFS metrics",
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "Peer",
    "query": "label_values(container_last_seen, pod)"
   }
  ]
 },
 "panels": [
  { "title": "HTTP Request", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "IPFS HTTP Response Size per Peer",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "yaxes": [
    { "format": "decbytes", "label": "Total size" }
   ],
   "targets": [
    {
     "expr": "ipfs_http_response_size_bytes_sum{pod=~\"^$Peer$\"}",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "IPFS HTTP Response Size Rate per Hour",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
   "yaxes": [
    { "format": "decbytes", "label": "Response Size/h" }
   ],
   "targets": [
    {
     "expr": "sum(increase(ipfs_http_response_size_bytes[1h]))",
     "legendFormat": "Response Size/h"
    }
   ]
  },
  {
   "title": "Total IPFS GET Requests",
   "type": "graph",
   "gridPos": { "h": 16, "w": 8, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(ipfs_http_requests_total{pod=~\"^$Peer$\", method=\"get\"}) by (pod)",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Total IPFS POST Requests",
   "type": "graph",
   "gridPos": { "h": 16, "w": 8, "x": 8, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(ipfs_http_requests_total{pod=~\"^$Peer$\", method=\"post\"}) by (pod)",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "p2p Total peers",
   "type": "graph",
   "gridPos": { "h": 16, "w": 8, "x": 16, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "ipfs_p2p_peers_total{pod=~\"^$Peer$\", transport=\"/ip4/tcp\"}",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Average HTTP Request Duration",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 25 },
   "yaxes": [
    { "format": "s", "label": "Duration" }
   ],
   "targets": [
    {
     "expr": "ipfs_http_request_duration_seconds_sum / ipfs_http_request_duration_seconds_count",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  { "title": "Datastore", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 33 } },
  {
   "title": "Average Datastore Latency",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 34 },
   "yaxes": [
    { "format": "s", "label": "Duration" }
   ],
   "targets": [
    {
     "expr": "ipfs_fsrepo_datastore_get_latency_seconds_sum / ipfs_fsrepo_datastore_get_latency_seconds_count",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Average Datastore size",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 34 },
   "yaxes": [
    { "format": "decbytes", "label": "Size" }
   ],
   "targets": [
    {
     "expr": "ipfs_fsrepo_datastore_get_size_bytes_sum / ipfs_fsrepo_datastore_get_size_bytes_count",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Total Datastore Delete",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 42 },
   "yaxes": [
    { "format": "short", "label": "Total number of delete" }
   ],
   "targets": [
    {
     "expr": "sum(ipfs_fsrepo_datastore_delete_total{pod=~\"^$Peer$\"}) by (pod)",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Datastore Query",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 42 },
   "yaxes": [
    { "format": "short", "label": "Total number of queries" }
   ],
   "targets": [
    {
     "expr": "sum(ipfs_fsrepo_datastore_query_total{pod=~\"^$Peer$\"}) by (pod)",
     "legendFormat": "{{pod}}"
    }
   ]
  }
 ]
}