{
 "title": "Peer Metrics",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   {
    "name": "Peer",
    "label": "Peer",
    "query": "label_values(container_last_seen, pod)"
   }
  ]
 },
 "panels": [
  {
   "title": "Peers Active",
   "type": "graph",
   "gridPos": { "h": 15, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short", "label": "Total Number of Active Peers" }
   ],
   "targets": [
    {
     "expr": "count(container_last_seen{container!=\"POD\", container=\"peer\", pod=~\"peer.*\"}) by (pod)",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Average Accuracy",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(peer_consensus_accuracy_percent_sum) / sum(peer_consensus_accuracy_percent_count)",
     "legendFormat": "consensus accuracy"
    },
    {
     "expr": "sum(peer_model_accuracy_percent_sum) / sum(peer_model_accuracy_percent_count)",
     "legendFormat": "model accuracy"
    }
   ]
  },
  {
   "title": "Peer Pods",
   "type": "stat",
   "gridPos": { "h": 7, "w": 3, "x": 18, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "count(container_last_seen{container!=\"POD\", container=\"peer\", pod=~\"peer.*\"})"
    }
   ]
  },
  {
   "title": "Exited Subscribers",
   "type": "stat",
   "gridPos": { "h": 7, "w": 3, "x": 21, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(peer_subscribers_exit_total{pod=~\".+\"})"
    }
   ]
  },
  {
   "title": "Average Loss",
   "type": "graph",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 7 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(peer_consensus_model_loss_percent_sum) / sum(peer_consensus_model_loss_percent_count)",
     "legendFormat": "consensus model loss"
    },
    {
     "expr": "sum(peer_model_loss_percent_sum) / sum(peer_model_loss_percent_count)",
     "legendFormat": "model loss"
    }
   ]
  },
  { "title": "Transaction", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 15 } },
  {
   "title": "Transactions Published",
   "type": "graph",
   "gridPos": { "h": 8, "w": 18, "x": 0, "y": 16 },
   "yaxes": [
    { "format": "short", "label": "Total number of transactions" }
   ],
   "targets": [
    {
     "expr": "sum((peer_transactions_published_total{pod=~\"^$Peer$\"})) by (pod)",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Optimal received transactions",
   "type": "stat",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 16 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum (peer_transactions_published_total)* (sum (peer_subscribers_total))"
    }
   ]
  },
  {
   "title": "Transactions Published per Hour",
   "type": "graph",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 24 },
   "yaxes": [
    { "format": "short", "label": "Transactions/h" }
   ],
   "targets": [
    {
     "expr": "sum(increase(peer_transactions_published_total[1h]))",
     "legendFormat": "Transaction/h"
    }
   ]
  },
  {
   "title": "Publish Errors",
   "type": "graph",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 24 },
   "yaxes": [
    { "format": "short", "label": "Total number of publish errors" }
   ],
   "targets": [
    {
     "expr": "sum(peer_publish_error_total{pod=~\"^$Peer$\"}) by (pod)",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Transactions Received per Hour",
   "type": "graph",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 24 },
   "yaxes": [
    { "format": "short", "label": "Transactions/h" }
   ],
   "targets": [
    {
     "expr": "sum(increase(peer_transactions_received_total{pod=~\".+\"}[1h]))",
     "legendFormat": "Transaction/h"
    }
   ]
  },
  { "title": "Training", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 32 } },
  {
   "title": "Trainings",
   "type": "graph",
   "gridPos": { "h": 8, "w": 18, "x": 0, "y": 33 },
   "yaxes": [
    { "format": "short", "label": "Total number of training" }
   ],
   "targets": [
    {
     "expr": "sum(peer_trainings_total{pod=~\"^$Peer$\"}) by (pod)",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Trainings per Hour",
   "type": "graph",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 33 },
   "yaxes": [
    { "format": "short", "label": "Training/h" }
   ],
   "targets": [
    {
     "expr": "sum(increase(peer_trainings_total{pod=~\".+\"}[1h]))",
     "legendFormat": "Training/h"
    }
   ]
  },
  {
   "title": "Average Training Time",
   "type": "graph",
   "gridPos": { "h": 8, "w": 5, "x": 0, "y": 41 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "sum(peer_training_time_seconds_sum / peer_training_time_seconds_count) by (pod)",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Average time between training",
   "type": "graph",
   "gridPos": { "h": 8, "w": 7, "x": 5, "y": 41 },
   "yaxes": [
    { "format": "s", "label": "Duration" }
   ],
   "targets": [
    {
     "expr": "sum (peer_time_between_training_seconds_sum / peer_time_between_training_seconds_count) by (pod)",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Training Error",
   "type": "graph",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 41 },
   "yaxes": [
    { "format": "short", "label": "Total number of errors" }
   ],
   "targets": [
    {
     "expr": "sum(peer_training_error_total{pod=~\"^$Peer$\"}) by (pod)",
     "legendFormat": "{{pod}}"
    }
   ]
  }
 ]
}