FROM yrzr/go-ipfs-arm64v8:v0.6.0

COPY entrypoint /entrypoint
COPY config /config

EXPOSE 4001

RUN chmod +x /entrypoint
ENTRYPOINT [ "/sbin/tini", "--", "/entrypoint" ]
CMD [ "daemon", "--migrate=true", "--enable-pubsub-experiment", "--enable-gc" ]
